syntax = "proto3";
package minino.rpc;

import "about/about.proto";
import "wifi/analyzer/analyzer.proto";

enum Status {
  STATUS_UNKNOWN = 0;
  STATUS_OK = 1;
  STATUS_ERROR = 2;
}

message MainRequest {

  uint32 message_id = 100;
  Status status = 101;

  oneof payload {
    minino.about.AboutRequest about = 1;
    minino.analyzer.AnalyzerStartRequest analyzer_start = 2;
    minino.analyzer.AnalyzerStopRequest analyzer_stop = 3;
    minino.analyzer.AnalyzerSetChannelRequest analyzer_set_channel = 4;
  }
}

message MainResponse {
  uint32 message_id = 100;
  Status status = 101;

  oneof payload {
    minino.about.AboutResponse about = 1;
    minino.analyzer.AnalyzerData analyzer = 2;
  }
}