// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pruebas.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tutorial;

@kotlin.jvm.JvmName("-initializeperson")
public inline fun person(block: tutorial.PersonKt.Dsl.() -> kotlin.Unit): tutorial.Pruebas.Person =
  tutorial.PersonKt.Dsl._create(tutorial.Pruebas.Person.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `tutorial.Person`
 */
public object PersonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tutorial.Pruebas.Person.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tutorial.Pruebas.Person.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tutorial.Pruebas.Person = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `int32 id = 2;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `int32 id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string email = 3;`
     */
    public var email: kotlin.String
      @kotlin.jvm.JvmName("getEmail")
        get() = _builder.email
      @kotlin.jvm.JvmName("setEmail")
        set(value) {
        _builder.email = value
      }
    /**
     * `string email = 3;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun tutorial.Pruebas.Person.copy(block: `tutorial`.PersonKt.Dsl.() -> kotlin.Unit): tutorial.Pruebas.Person =
  `tutorial`.PersonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

