// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: simple.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package simple;

