// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: simple.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package simple;

@kotlin.jvm.JvmName("-initializesimpleMessage")
public inline fun simpleMessage(block: simple.SimpleMessageKt.Dsl.() -> kotlin.Unit): simple.Simple.SimpleMessage =
  simple.SimpleMessageKt.Dsl._create(simple.Simple.SimpleMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `simple.SimpleMessage`
 */
public object SimpleMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: simple.Simple.SimpleMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: simple.Simple.SimpleMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): simple.Simple.SimpleMessage = _builder.build()

    /**
     * `required int32 lucky_number = 1;`
     */
    public var luckyNumber: kotlin.Int
      @kotlin.jvm.JvmName("getLuckyNumber")
        get() = _builder.luckyNumber
      @kotlin.jvm.JvmName("setLuckyNumber")
        set(value) {
        _builder.luckyNumber = value
      }
    /**
     * `required int32 lucky_number = 1;`
     */
    public fun clearLuckyNumber() {
      _builder.clearLuckyNumber()
    }
    /**
     * `required int32 lucky_number = 1;`
     * @return Whether the luckyNumber field is set.
     */
    public fun hasLuckyNumber(): kotlin.Boolean {
      return _builder.hasLuckyNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun simple.Simple.SimpleMessage.copy(block: `simple`.SimpleMessageKt.Dsl.() -> kotlin.Unit): simple.Simple.SimpleMessage =
  `simple`.SimpleMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

