// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ejemplo;

@kotlin.jvm.JvmName("-initializedatosMensaje")
public inline fun datosMensaje(block: ejemplo.DatosMensajeKt.Dsl.() -> kotlin.Unit): ejemplo.Protobuf.DatosMensaje =
  ejemplo.DatosMensajeKt.Dsl._create(ejemplo.Protobuf.DatosMensaje.newBuilder()).apply { block() }._build()
/**
 * ```
 * El mensaje con las dos variables de texto (string)
 * ```
 *
 * Protobuf type `ejemplo.DatosMensaje`
 */
public object DatosMensajeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ejemplo.Protobuf.DatosMensaje.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ejemplo.Protobuf.DatosMensaje.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ejemplo.Protobuf.DatosMensaje = _builder.build()

    /**
     * ```
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * ```
     *
     * `string hi = 1;`
     */
    public var hi: kotlin.String
      @kotlin.jvm.JvmName("getHi")
        get() = _builder.hi
      @kotlin.jvm.JvmName("setHi")
        set(value) {
        _builder.hi = value
      }
    /**
     * ```
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * ```
     *
     * `string hi = 1;`
     */
    public fun clearHi() {
      _builder.clearHi()
    }

    /**
     * `string Bye = 2;`
     */
    public var bye: kotlin.String
      @kotlin.jvm.JvmName("getBye")
        get() = _builder.bye
      @kotlin.jvm.JvmName("setBye")
        set(value) {
        _builder.bye = value
      }
    /**
     * `string Bye = 2;`
     */
    public fun clearBye() {
      _builder.clearBye()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ejemplo.Protobuf.DatosMensaje.copy(block: `ejemplo`.DatosMensajeKt.Dsl.() -> kotlin.Unit): ejemplo.Protobuf.DatosMensaje =
  `ejemplo`.DatosMensajeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

