// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf.proto
// Protobuf Java Version: 4.32.0

package ejemplo;

@com.google.protobuf.Generated
public final class Protobuf {
  private Protobuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      Protobuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DatosMensajeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ejemplo.DatosMensaje)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * </pre>
     *
     * <code>string hi = 1;</code>
     * @return The hi.
     */
    java.lang.String getHi();
    /**
     * <pre>
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * </pre>
     *
     * <code>string hi = 1;</code>
     * @return The bytes for hi.
     */
    com.google.protobuf.ByteString
        getHiBytes();

    /**
     * <code>string Bye = 2;</code>
     * @return The bye.
     */
    java.lang.String getBye();
    /**
     * <code>string Bye = 2;</code>
     * @return The bytes for bye.
     */
    com.google.protobuf.ByteString
        getByeBytes();
  }
  /**
   * <pre>
   * El mensaje con las dos variables de texto (string)
   * </pre>
   *
   * Protobuf type {@code ejemplo.DatosMensaje}
   */
  public static final class DatosMensaje extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ejemplo.DatosMensaje)
      DatosMensajeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        DatosMensaje.class.getName());
    }
    // Use DatosMensaje.newBuilder() to construct.
    private DatosMensaje(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DatosMensaje() {
      hi_ = "";
      bye_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ejemplo.Protobuf.internal_static_ejemplo_DatosMensaje_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ejemplo.Protobuf.internal_static_ejemplo_DatosMensaje_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ejemplo.Protobuf.DatosMensaje.class, ejemplo.Protobuf.DatosMensaje.Builder.class);
    }

    public static final int HI_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hi_ = "";
    /**
     * <pre>
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * </pre>
     *
     * <code>string hi = 1;</code>
     * @return The hi.
     */
    @java.lang.Override
    public java.lang.String getHi() {
      java.lang.Object ref = hi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hi_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * string: tipo de dato para texto
     * 1 y 2: números de campo únicos, importantes para la codificación binaria
     * </pre>
     *
     * <code>string hi = 1;</code>
     * @return The bytes for hi.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHiBytes() {
      java.lang.Object ref = hi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bye_ = "";
    /**
     * <code>string Bye = 2;</code>
     * @return The bye.
     */
    @java.lang.Override
    public java.lang.String getBye() {
      java.lang.Object ref = bye_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bye_ = s;
        return s;
      }
    }
    /**
     * <code>string Bye = 2;</code>
     * @return The bytes for bye.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getByeBytes() {
      java.lang.Object ref = bye_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bye_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hi_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, hi_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bye_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, bye_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hi_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, hi_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bye_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, bye_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ejemplo.Protobuf.DatosMensaje)) {
        return super.equals(obj);
      }
      ejemplo.Protobuf.DatosMensaje other = (ejemplo.Protobuf.DatosMensaje) obj;

      if (!getHi()
          .equals(other.getHi())) return false;
      if (!getBye()
          .equals(other.getBye())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HI_FIELD_NUMBER;
      hash = (53 * hash) + getHi().hashCode();
      hash = (37 * hash) + BYE_FIELD_NUMBER;
      hash = (53 * hash) + getBye().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ejemplo.Protobuf.DatosMensaje parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ejemplo.Protobuf.DatosMensaje parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ejemplo.Protobuf.DatosMensaje parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ejemplo.Protobuf.DatosMensaje prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * El mensaje con las dos variables de texto (string)
     * </pre>
     *
     * Protobuf type {@code ejemplo.DatosMensaje}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ejemplo.DatosMensaje)
        ejemplo.Protobuf.DatosMensajeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ejemplo.Protobuf.internal_static_ejemplo_DatosMensaje_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ejemplo.Protobuf.internal_static_ejemplo_DatosMensaje_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ejemplo.Protobuf.DatosMensaje.class, ejemplo.Protobuf.DatosMensaje.Builder.class);
      }

      // Construct using ejemplo.Protobuf.DatosMensaje.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        hi_ = "";
        bye_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ejemplo.Protobuf.internal_static_ejemplo_DatosMensaje_descriptor;
      }

      @java.lang.Override
      public ejemplo.Protobuf.DatosMensaje getDefaultInstanceForType() {
        return ejemplo.Protobuf.DatosMensaje.getDefaultInstance();
      }

      @java.lang.Override
      public ejemplo.Protobuf.DatosMensaje build() {
        ejemplo.Protobuf.DatosMensaje result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ejemplo.Protobuf.DatosMensaje buildPartial() {
        ejemplo.Protobuf.DatosMensaje result = new ejemplo.Protobuf.DatosMensaje(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ejemplo.Protobuf.DatosMensaje result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hi_ = hi_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bye_ = bye_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ejemplo.Protobuf.DatosMensaje) {
          return mergeFrom((ejemplo.Protobuf.DatosMensaje)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ejemplo.Protobuf.DatosMensaje other) {
        if (other == ejemplo.Protobuf.DatosMensaje.getDefaultInstance()) return this;
        if (!other.getHi().isEmpty()) {
          hi_ = other.hi_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getBye().isEmpty()) {
          bye_ = other.bye_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                hi_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                bye_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object hi_ = "";
      /**
       * <pre>
       * string: tipo de dato para texto
       * 1 y 2: números de campo únicos, importantes para la codificación binaria
       * </pre>
       *
       * <code>string hi = 1;</code>
       * @return The hi.
       */
      public java.lang.String getHi() {
        java.lang.Object ref = hi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * string: tipo de dato para texto
       * 1 y 2: números de campo únicos, importantes para la codificación binaria
       * </pre>
       *
       * <code>string hi = 1;</code>
       * @return The bytes for hi.
       */
      public com.google.protobuf.ByteString
          getHiBytes() {
        java.lang.Object ref = hi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * string: tipo de dato para texto
       * 1 y 2: números de campo únicos, importantes para la codificación binaria
       * </pre>
       *
       * <code>string hi = 1;</code>
       * @param value The hi to set.
       * @return This builder for chaining.
       */
      public Builder setHi(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hi_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string: tipo de dato para texto
       * 1 y 2: números de campo únicos, importantes para la codificación binaria
       * </pre>
       *
       * <code>string hi = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHi() {
        hi_ = getDefaultInstance().getHi();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string: tipo de dato para texto
       * 1 y 2: números de campo únicos, importantes para la codificación binaria
       * </pre>
       *
       * <code>string hi = 1;</code>
       * @param value The bytes for hi to set.
       * @return This builder for chaining.
       */
      public Builder setHiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hi_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object bye_ = "";
      /**
       * <code>string Bye = 2;</code>
       * @return The bye.
       */
      public java.lang.String getBye() {
        java.lang.Object ref = bye_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bye_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Bye = 2;</code>
       * @return The bytes for bye.
       */
      public com.google.protobuf.ByteString
          getByeBytes() {
        java.lang.Object ref = bye_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bye_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Bye = 2;</code>
       * @param value The bye to set.
       * @return This builder for chaining.
       */
      public Builder setBye(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bye_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string Bye = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBye() {
        bye_ = getDefaultInstance().getBye();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string Bye = 2;</code>
       * @param value The bytes for bye to set.
       * @return This builder for chaining.
       */
      public Builder setByeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bye_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ejemplo.DatosMensaje)
    }

    // @@protoc_insertion_point(class_scope:ejemplo.DatosMensaje)
    private static final ejemplo.Protobuf.DatosMensaje DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ejemplo.Protobuf.DatosMensaje();
    }

    public static ejemplo.Protobuf.DatosMensaje getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DatosMensaje>
        PARSER = new com.google.protobuf.AbstractParser<DatosMensaje>() {
      @java.lang.Override
      public DatosMensaje parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DatosMensaje> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DatosMensaje> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ejemplo.Protobuf.DatosMensaje getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ejemplo_DatosMensaje_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ejemplo_DatosMensaje_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protobuf.proto\022\007ejemplo\"\'\n\014DatosMensaj" +
      "e\022\n\n\002hi\030\001 \001(\t\022\013\n\003Bye\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ejemplo_DatosMensaje_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ejemplo_DatosMensaje_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ejemplo_DatosMensaje_descriptor,
        new java.lang.String[] { "Hi", "Bye", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
